CREATE TABLE department
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name VARCHAR(255),
    is_closed       BOOLEAN,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE department_person_list
(
    department_id  INTEGER NOT NULL,
    person_list_id INTEGER NOT NULL
);

CREATE TABLE person
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(255),
    age           INTEGER,
    department_id INTEGER,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

ALTER TABLE department_person_list
    ADD CONSTRAINT uc_department_person_list_personlist UNIQUE (person_list_id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE department_person_list
    ADD CONSTRAINT fk_depperlis_on_department FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE department_person_list
    ADD CONSTRAINT fk_depperlis_on_person FOREIGN KEY (person_list_id) REFERENCES person (id);